public class CommonConstants {
    
    public static final Integer STATUS_CODE_401 = 401;
    public static final Integer STATUS_CODE_200 = 200;
    public static final String ERR_TOKEN_EXPIRED = 'jwt_token_expired';
    public static final String ERR_TOKEN_VERIFICATION_FAILED = 'jwt_token_verification_failed';
    public static final String STATUS_MSG_OK = 'OK';
    public static final String SESSION_CACHE = 'local.CreditNotePartition';
    public static final String CACHE_ACCESS_TOKEN = 'AccessTokenCreditNote';
    public static final String CUSTOM_SETTING_PAYMENT_WEB = 'PaymentWeb';
    public static final String CUSTOM_SETTING_Digitoll = 'Digitoll';
    public static final String POST_METHOD = 'POST';
    public static final String PUT_METHOD = 'PUT';
    public static final String GET_METHOD = 'GET';
    public static final String NAMED_CRED_REQUEST_DATA = 'callout:CreditNote_RequestData';
    public static final String NAMED_CRED_REQUEST_TOKEN = 'callout:CreditNote';
    public static final String USERNAME = 'userName';
    public static final String EMAIL_ADDRESS = 'emailAddress';
    public static final String PHONE_Number = 'phoneNumber';
    public static final String ORDER_NUMBER = 'orderNumber';
    public static final String SHIPMENT_NUMBER = 'shipmentNumber';
    public static final String TRANSACTION_ID = 'transactionId';
    public static final String TRANSACTION_DATE = 'transactionDate';
    public static final String TRANSACTION_AMOUNT = 'transactionAmount';
    public static final String ORDER_ID = 'orderId';
    public static final String BLANK = '';
    public static final String TOKEN = 'token';
    public static final String SLASH = '/';
    public static final String CREDITED = 'credited';
    public static final String TRANSACTION_STATUS_CANCELLED = 'cancelled';
    public static final String NAMED_CRED_SEND_TRANSACTION_ID = 'callout:CreditNote_SendTransactionId/';
    public static final String APPLICATION_JSON = 'application/json';
    public static final String ORDER_TYPE = 'orderType';
    public static final String CURRENCY_CODE = 'currencyCode';
    public static final String CONSIGNMENT_NUMBER = 'consignmentNumber';
    public static final String QUESTION_MARK = '?';
    public static final String STATUS = 'status';
    public static final String EQUALTO = '=';
    public static final String DOUBLE_ATRATE_SPILT = '@@';
    public static final String ORDER_REFUND = 'Order Refund';
    public static final String DIGITAL_STAMPS = 'Digital Stamps';
    // Adding New String Constants - PAYMENT_PROVIDER and PAYMENT_TYPE
    public static final String PAYMENT_PROVIDER = 'paymentProvider';
    public static final String PAYMENT_TYPE = 'paymentType';

}