public with sharing class crm_NPS_Request_Type {
	
	public string CustomerID = '';
	public string CustomerNumber ='';
	public string CustomerPhone ='';
	public string CustomerCountry = '';
	public string CustomerName = '';
	
	public string ActivityID = '';
	public string ActivityName = '';
	public string ActivityType = '';
	public string ActivityCategory = '';
	public string ActivityStart;
	public string ActivityEnd;
	public string ActivityCustomerService = '';
	public string ActivitySegment = '';
	public string ActivitySubSegment = '';
	
	public string BusinessID = '';
	public string BusinessDescritpion = '';
	public string BusinessStatus = '';
	public string BusinessType = '';
	public string BusinessProduct = '';
	public string BusinessValue = '';
	public string BusinessCustomerService = '';
	public string BusinessSegment = '';
	public string BusinessSubSegment = '';
	
	public string ActivityResponsibleCaesarUserID = '';
	public string ActivityResponsibleFirstName = '';
	public string ActivityResponsibleSurname = '';
	public string ActivityResponsibleUnit = '';
	
	public string ContactID = '';
	public string ContactFirstName = '';
	public string ContactSurname = '';
	public string ContactPhoneMobile = '';
	public string ContactEmail = '';
	
    
}