public class OppToPricingTool_Wrapper {

    public List<opp_CustomerDetails> customerData;
    
    public class opp_CustomerDetails{
        Public String function;
        Public String partyId;
        Public String orgNo;
        Public String partyName;
        Public String partyCountry;
        Public String partyCountryId;
        Public String opportunityId;
        Public String opportunityName;
        Public String sellerId;
        Public String sellerName;
        Public String oppCurrency;
        Public String serviceFamily;
        Public String serviceGroup;
        Public String opportunityDate;
        Public String opportunityType;
    }
    
}